### ISSUE TITLE
Move JavaScript files out of template directory

### ISSUE THREAD

**Issue by markroth8** [VisitData-org/ca_visit_tracking#110]
In #109, we moved the JS files into the templates directory so that they can get the URL of the bucket-hosted data. This issue is to move them back to static files and get the URL from another JS module or from metadata in the parent  HTML page.

**Comment by anusheel** [comment]
Is there value in moving to a framework like React? Depends on the roadmap on the front-end side and the anticipated complexity.

**Comment by dsjoerg** [comment]
Currently our primary known users are on our team, Joe Cua and Noah Millman, who are using the product daily to analyze trends for our first client.  They are operating on desktop web with high bandwidth and are sophisticated.

Our first client's roadmap includes wishlists for new ways to slice, cut and aggregate the Foursquare data which then we'd be providing ways to visualize.

Future users may be county health officers, smaller-state teams and mayoral teams using mobile devices in lower-bandwidth situations and less sophisticated analytically.  Maybe our product bifurcates.  Really unclear.

**Comment by dsjoerg** [comment]
If Foursquare (or any other vendor) can make a new data product for us, it will take them at least a day to make it, so we'll have at least a day's warning to put together the front end for looking at it.
