### ISSUE TITLE
Link from FAQ for raw data is broken

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#121]

**Comment by markroth8** [comment]
The README points to the latest data. Data is available at gs://data.visitdata.org/processed/vendor/foursquare/asof/20200405-v0/ also accessible via HTTPS at https://data.visitdata.org/processed/vendor/foursquare/asof/20200405-v0/.

The `20200405-v0` is a snapshot id.

We should update the FAQ accordingly.

We may want to wait for #123 as this will give us a better story for browsing the raw data.
