### ISSUE TITLE
HSTS / bare domain default

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#122]
From a random person to Dennis:
"Couldn’t help but notice the default for visitdata.org is the http:// which I understand may work better in some countries w/ strict encryption requirements. Just wanted to see if that was on purpose. I did see https:// is supported but it wasn’t using HSTS yet so just wanted to check in. Awesome work btw!"

**Comment by markroth8** [comment]
We should consider this, but as HSTS is permanent for at least 1 year, I'd rather wait until the site itself is a bit more permanent. Meanwhile, we can at least redirect from http to https.

**Comment by markroth8** [comment]
The bare domain default portion of this is addressed in #138

**Comment by markroth8** [comment]
Now the http to https redirect is addressed in #138 as well.

**Comment by markroth8** [comment]
Now that I think about it, I think the 301 redirect is good enough for visitdata.org so I'm marking #138 as closing this issue.
