### ISSUE TITLE
setnavlinks looks like has a bug

### ISSUE THREAD

**Issue by ajanian** [VisitData-org/ca_visit_tracking#130]
When you are on a county in county/grouped and switch to county/all that county used to track.  That code was in the following.  I don't have time to find the bug right now.

`function setNavLinks() {
  // TODO fix the nav links to handle the new state stuff
  document.getElementById('nav-chartgrouped').href = "/bydatesel/" + encodeURIComponent(selectedState) + "/ALL/ALL";
  document.getElementById('nav-chartall').href = "/bydatesel/" + encodeURIComponent(selectedState) + "/ALL/ALL?datafilename=raw";
  document.getElementById('nav-stategrouped').href = "/bystatesel/" + encodeURIComponent(selectedState) + "/ALL";
  document.getElementById('nav-stateall').href = "/bystatesel/" + encodeURIComponent(selectedState) + "/ALL?datafilename=raw";
}`

**Comment by jaked** [comment]
I think it was broken previously—the `setNavLinks` function was identical in `all_state.js` and `state_bydate.js`. But I see what needs fixing, I'll take it.

**Comment by ajanian** [comment]
thanks.  I thought it may have been broken before
