### ISSUE TITLE
Washington D.C.

### ISSUE THREAD

**Issue by vedinerd** [VisitData-org/ca_visit_tracking#135]
Hi -- thank you for your efforts and this excellent service!  I'm unable to locate data for Washington D.C., however -- do any of you know where it might be in this data set?  Or is it just not included.  There isn't a separate "state" entry for it, and the district doesn't seem to appear as a county in the Maryland or Virginia files.  I apologize if I'm missing something obvious here.  Thank you!

**Comment by ajanian** [comment]
we are working with our data partners to get the DC data.  Unfortunately it isn't currently included.

**Comment by vedinerd** [comment]
Great, thanks for the response and information.
