### ISSUE TITLE
See examples of venue categories

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#154]
People are endlessly and rightfully asking what the venue categories mean.

The easiest way to explain is by showing them examples.

We need a way, given a venue category or venue category group, to see examples of that in a given county or state.

It's actually not hard to construct a URL that shows exactly this!

Here are big box stores in Santa Clara County.

https://foursquare.com/explore?mode=url&near=San%20Jose%2C%20CA%2C%20United%20States&nearGeoId=72057594043320107&q=Big%20box%20stores

Constructing the URL correctly may not be possible for some of the venue groups.  For that we may need to get more creative, and give a list of URLs for each of the sub-categories contained in that group.

**Comment by dsjoerg** [comment]
It seems weird to me, looking at https://beta.visitdata.org/venuegroupdetails?state=California&county=
that "Big Box Stores" is a top-level group containing "Big Box Store"
and yet "Shops & Services" is another top-level group containing "Big Box Store".

What's going on here?  Bug on our side?  Bug on their side?  Feature, not bug?

**Comment by dsjoerg** [comment]
@ajanian maybe you understand what's happening?

**Comment by ajanian** [comment]
no idea.  As you probably all remember I've thought grouped was a bad idea from the beginning :-) I think the groups are naturally already there in the taxonomy and, if not, we should work with FSQ to put them in.  I think the reason they did it is because some of the other groups are too sparse if they aren't rolled up?  But I find the grouping to be a black box even though there is a spec

**Comment by dsjoerg** [comment]
@robertobuso described to me last night the manual process he went through to create `templates/venuegroupdetails.html`.   I think all that remains to be done is to clean it up a little — as per [Foursquare's doc](https://docs.google.com/document/d/15uN-_r6n9egh3kuZgEOwAKrrFGEJcwuCPy0KWmaFiXw/edit?via_commande=true) (look at the SQL-like code at the end), anything that is matched by an earlier rule is not matched by a later rule.  So for example Big Box Stores are grouped as "Big Box Store" and nothing else.  So they should NOT go into "Shops & Services".

So the remaining clean-up to be done is to go through `templates/venuegroupdetails.html` and confirm that each venue type only appears once, and manually resolve it correctly when they don't.  Or redo `templates/venuegroupdetails.html` with a bit of code that basically implements the logic of [Foursquare's doc](https://docs.google.com/document/d/15uN-_r6n9egh3kuZgEOwAKrrFGEJcwuCPy0KWmaFiXw/edit?via_commande=true) on each of the venue types.

**Comment by ajanian** [comment]
@robertobuso and @dsjoerg I think this is done, right?  I believe it was done a while back.  I'm trying to get things cleaned up so we are in a position to make updates to the site if/when it is really needed again
