### ISSUE TITLE
beta.visitdata.org doesnt permit seeing all counties for a particular venuetype

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#162]
https://visitdata.org/bydatesel/California/ALL/Beach works
https://beta.visitdata.org/bydatesel/California/ALL/Beach does not

perhaps @ajanian knows why?

**Comment by ajanian** [comment]
Ahhhh, yes.  So I mentioned this in the comments when I initially implemented this.  Because these files are much bigger we aren't able to load all of the data for all of the permutations.  So there is a file per county and then one file for the state with no county information.  I can maybe make this plot the single line for Beach visits for the whole state.  But we can't provide the same functionality (easily) where the link you provided shows Beach data for every county.

**Comment by dsjoerg** [comment]
This would take some additional work, but if I understand correctly, the only additional information we have in cubeV2 that we care about is median (aka p50).  So maybe the files don't need to be much larger than they used to be?

**Comment by dsjoerg** [comment]
I.e. we're not using the hour column, we're only taking hour = All.

And we're ignoring zipcode stuff, ignoring avg duration, and ignoring all the hour histogram stuff.

**Comment by ajanian** [comment]
All true. I just don’t have time to make those changes until late tomorrow. Requires focus and sitting with it and running through all the test cases in my head again

**Comment by ajanian** [comment]
given some sleep on this.  I think the easiest path forward is for @mattjacobus (if he can) to use the new cubev2 files to massage them into files that look closer to the old (non-cube) files.  We would drop the columns we aren't using and only keep the rows for the various demos and not the rows for the hours?

I think the output for matt's cube python script would be a relatively small change:
1) continue to produce the exact same county files as you are - we can use those for deeper dives into counties
2) keep the state file as-is
3) create a new state file to have rows for each {county|demo|location} key using ""/All for hours

Let me know if you guys want to chat about this.  I could make the site changes pretty easily given this change to the cube shredder

for the columns I need:
`function parseGroupedRow(stateOrCounty, row) {
  return {
    date: row.date,
    state: row.state,
    county: row.county,
    location_type: row.categoryname,
    p50Duration: row.p50Duration,
    meanDuration: row.avgDuration,
    hour: row.hour,
    essential: isGroupedCategoryEssential(row.categoryname),
    num_visits: row.visits,
    age: row.demo,
    datenum: datenum(row.date)
  };
}

function parseRawRow(stateOrCounty, row) {
  return {
    date: row.date,
    state: row.state,
    county: row.county,
    location_type: row.categoryname,
    p50Duration: row.p50Duration,
    meanDuration: row.avgDuration,
    hour: row.hour,
    essential: isCategoryEssential(row.categoryid),
    num_visits: row.visits,
    age: row.demo,
    datenum: datenum(row.date)
  };
}`

**Comment by dsjoerg** [comment]
It has been fixed!  https://visitdata.org/bydatesel/California/ALL/Beach is beautiful.  Thank you @ajanian and @mattjacobus

**Comment by anusheel** [comment]
And the low traffic in the week in the middle is explained by rain and a dip in temperature that weekend. Could we also add count of new cases in these graphs? Taking into account the average gestation period before symptoms show, it might be possible to draw a clear correlation between a spike in visits to beach with a spike in cases a few days later.

<img width="1074" alt="Screen Shot 2020-05-07 at 8 03 22 PM" src="https://user-images.githubusercontent.com/442372/81365753-df5e8400-909d-11ea-92aa-fa839f45e883.png">

**Comment by dsjoerg** [comment]
Very cool @anusheel !

Adding case counts would be fun.  Alternatively, adding an export capability.
