### ISSUE TITLE
Data has not been updated since 2020-04-25

### ISSUE THREAD

**Issue by BillPetti** [VisitData-org/ca_visit_tracking#165]
Thanks a ton for making this data available.

I am noticing that the data [here](https://visitdata.org/data) hasn't been updated since 2020-04-25. Is there an irregular cadence of updating, or should data generally be available the next day from the day before?

**Comment by ajanian** [comment]
we are in the process of updating and improving the data - that is the cause of the delay.  Usually the data will be updated by the following business day.  Hopefully by the end of the day today there will be new and improved data with the history filled in.  stay tuned!

Andrew

**Comment by BillPetti** [comment]
Awesome, appreciate it!
