### ISSUE TITLE
Selecting venue type of Travel/Transport clears state

### ISSUE THREAD

**Issue by dfoulser** [VisitData-org/ca_visit_tracking#171]
After selecting Venue type = Travel/Transport, my selected state is cleared and the state menu is empty. I must go back to the map and reselect my state to get started again.

Repro steps:
- main map page, select California
- venue type = travel/transport
- UI resets and menus are empty

View after making the menu selection. There is no graph.

![Screenshot_20200502-090322](https://user-images.githubusercontent.com/4777460/80864945-1410ac80-8c54-11ea-83a7-73891bc19a50.png)

**Comment by ajanian** [comment]
Great catch.  Issue was that there was an '&' in the category name and the filename omits that.

**Comment by ajanian** [comment]
deployed fix to prod and beta

**Comment by dfoulser** [comment]
That was fast!
