### ISSUE TITLE
Automatically remove old versions from appengine

### ISSUE THREAD

**Issue by ajanian** [VisitData-org/ca_visit_tracking#181]
I tried to deploy this morning and there is a limit of 210 versions.  We need to removed (ideally automatically) the old versions.

The following code snipper is from [here](https://stackoverflow.com/questions/34499875/how-to-automatically-delete-old-google-app-engine-version-instances).  Don't worry about the Ruby reference :-)

```
gcloud app versions delete `gcloud app versions list | sed 's/  */:/g' | cut -f 2 -d : | tail -n +2 | ghead -n -5 | tr "\n" " "`
```

I think the best place for this is probably to run after delpoyment in the deploy.sh script.

**Comment by ajanian** [comment]
the command works well but just needs the --project os-covid in both commands.  This takes quite some time to run so it should really be run on each deployment to make things faster.

```
gcloud app versions delete --project os-covid `gcloud app versions list --project os-covid | sed 's/  */:/g' | cut -f 2 -d : | tail -n +2 | ghead -n -5 | tr "\n" " "`
```

**Comment by ajanian** [comment]
As I committed this I realized it uses ghead and not head to get the last 5.  @dsjoerg do you know a quick fix to get this to work with head in a portable way?  i.e. Mac and linux?

**Comment by dsjoerg** [comment]
I don't!  I had never heard of `ghead` before, WTH is that!!  Very sketchy.    I didn't realize that `head` wasn't everywhere.

**Comment by ajanian** [comment]
It is gnu head on mac.  Basically on mac they have a g-foo thing of every command that is the gnu version.  Mac is BSD!!!  Tell Christos to fix his stuff.  I have a solution to just replace head with ghead on my mac.
