### ISSUE TITLE
Table column layout jumps when changing age group selection

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#21]

**Comment by dfoulser** [comment]
I have a fix for this using table.redraw(true).  But I thought I saw someone else wanted to take the issue.  I don't want to step on anyone's work.  OK to issue PR?

**Comment by dsjoerg** [comment]
Awesome thanks @dfoulser!  Yes OK to issue PR.

I'm not aware of someone else working on it, but I've been behind on Slack.

If someone else is working on it, we'll apologize and let them know that the best way to coordinate is by assigning oneself to the issue.

**Comment by dfoulser** [comment]
Ah, now I understand. AFAICT I don't have privs to assign the issue to myself, likely the other collaborator didn't either.  FWIW I sent the PR.  Cheers.

**Comment by dfoulser** [comment]
Closed by #131 commit 391f9d9
