### ISSUE TITLE
Indicate weather on the chart somehow

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#32]
Idea from Michele.  So that we don't get fooled by drops that are weather related.
So, grab weather data for county somehow, and shade chart regions when it's rainy in that county.

**Comment by dsjoerg** [comment]
This is no longer experimental.  In the briefing books prepared for government they are specifically cross-correlating the visit data to the weather; streamlining this workflow would save time and perhaps give better insights.

We don't want to mistake a change caused by weather for a change caused by people getting sick of staying inside.

**Comment by dsjoerg** [comment]
Temperature, rain, cloud cover all could be relevant

**Comment by rustyconover** [comment]
Is there a preferred provider of historical weather data? 

Seems to have the current conditions:
https://www.weather.gov/documentation/services-web-api

It doesn't appear to yet have historical observations.

The Dark Sky API isn't accepting signups any more.

What lat/long locations are necessary to log?

**Comment by ajanian** [comment]
Great questions.  I think we really need weather data by state and by county - at least that is what we are plotting today.  I think there is probably a dataset that has a zip to use for a county/state or a lat long for a county/state.  I think we aren't trying to get tooooo accurate so something close will work.  I think there have been some ideas for weather datasets floating around here.  @mattjacobus and @dsjoerg probably know some.  If not, ask JeremyB in the slack - he's the all knowing data guy

**Comment by slyapustin** [comment]
I think we can use OpenWeather Historical Data: https://openweathermap.org/history

**Comment by rustyconover** [comment]
All of that historical weather seems to be part of a priced offering.  I'm happy to start archiving the current forecasts though.

https://openweathermap.org/price

**Comment by slyapustin** [comment]
I think we need to create some rating based on weather conditions.
For example: `Walkability`: 100% (No rain/snow, no strong wind and not too hot/cold) - 0% (Strong rain/snow, storm and etc).

I can create an API to get data from the data source and transfer it to that rating (need to work on the formula).

**Comment by dsjoerg** [comment]
Hmm... I suppose with more past data about mobility and weather, we could fit a `Walkability` model per state to understand how different parts of USA react to different weather conditions.

**Comment by dsjoerg** [comment]
But the simpler thing for now would be to show temperature and precipitation below the chart, and then people looking at it already know how from experience people in that region react to any given precipitation/temperature combination.

**Comment by slyapustin** [comment]
Found another data source: https://water.weather.gov/precip/download.php
It's in GRB and here is Python library to work with that data https://github.com/jswhit/pygrib

**Comment by ajanian** [comment]
Here is the punchlist as I see it to get weather data released.

1) We need to set up the ETL jobs to run on GCP (@markroth8 to help/review)
2) We need to backfill the historic weather data by copying from @anusheel bucket(s) to ours (@markroth8 to help/review)
3) We need to integrate the javascript and accept PR #168 (@ajanian to do)

**Comment by ajanian** [comment]
we have the puchlist issue #178 so this is done
