### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by markroth8** [VisitData-org/ca_visit_tracking#69]
It's our top 404 :)

**Comment by dsjoerg** [comment]
TOP PRIORITY

**Comment by ajanian** [comment]
Here's what I made for reference at https://favicon.io/favicon-generator/
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/99716/94732055-b8963800-0333-11eb-9124-9276e973eedb.png">
