### ISSUE TITLE
Post venue taxonomy on visitdata.org

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#72]
My brother looked at the data and asked "How is nightlife spot defined?"

**Comment by ajanian** [comment]
4d4b7105d754a06376d81259,Nightlife Spot,false

4bf58dd8d48988d116941735,Bar,false

52e81612bcbc57f1066b7a0d,Beach Bar,false

56aa371ce4b08b9a8d57356c,Beer Bar,false

4bf58dd8d48988d117941735,Beer Garden,false

52e81612bcbc57f1066b7a0e,Champagne Bar,false

4bf58dd8d48988d11e941735,Cocktail Bar,false

4bf58dd8d48988d118941735,Dive Bar,false

4bf58dd8d48988d1d8941735,Gay Bar,false

4bf58dd8d48988d119941735,Hookah Bar,false

4bf58dd8d48988d1d5941735,Hotel Bar,false

4bf58dd8d48988d120941735,Karaoke Bar,false

4bf58dd8d48988d11b941735,Pub,false

4bf58dd8d48988d11c941735,Sake Bar,false

4bf58dd8d48988d1d4941735,Speakeasy,false

4bf58dd8d48988d11d941735,Sports Bar,false

56aa371be4b08b9a8d57354d,Tiki Bar,false

4bf58dd8d48988d122941735,Whisky Bar,false

4bf58dd8d48988d123941735,Wine Bar,false

50327c8591d4c4b30a586d5d,Brewery,false

4bf58dd8d48988d121941735,Lounge,false

53e510b7498ebcb1801b55d4,Night Market,false

4bf58dd8d48988d11f941735,Nightclub,false

4bf58dd8d48988d11a941735,Other Nightlife,false

4bf58dd8d48988d1d6941735,Strip Club,false

**Comment by dsjoerg** [comment]
https://developer.foursquare.com/docs/build-with-foursquare/categories/
but there is some additional info on how groupings are made here: https://docs.google.com/document/d/15uN-_r6n9egh3kuZgEOwAKrrFGEJcwuCPy0KWmaFiXw/edit
